
CREATE TABLE MOVIES(
	ID SERIAL PRIMARY KEY,
	TITLE VARCHAR NOT NULL,
	YEAR INT NOT NULL
);

INSERT INTO MOVIES(TITLE, YEAR) VALUES ('Her', 2013);
INSERT INTO MOVIES(TITLE, YEAR) VALUES ('I, Robot', 2014);
INSERT INTO MOVIES(TITLE, YEAR) VALUES ('A.I. Artificial Intelligence', 2001);
INSERT INTO MOVIES(TITLE, YEAR) VALUES ('A Space Odyssey', 1968);
INSERT INTO MOVIES(TITLE, YEAR) VALUES ('Blade Runner', 1962);